# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 761e3f9de3aab6cd9e516d056fd2a7e27eaf43abf2a8004f0780fd766ee6e2847e848ebb414f88bbd47043e369672a43472e03b0742e17b84ed8bb9eeb355f3c

test:
  secret_key_base: 3ae994ca8360d46251f9214114fc0d5852b001e77f42e0be7fa909b93a89402c36e6257a0b93993e1b1c4761c3bde232485bd235441c4895cd003586ddf4e9f4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
